# Generated by Django 5.1.5 on 2025-01-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_society_address_remove_society_certificate_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.society')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.society')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(null=True)),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.society')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
