# Generated by Django 5.1.5 on 2025-01-31 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_complaint_event_memberpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='society',
        ),
        migrations.CreateModel(
            name='ComplaintReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.complaint')),
            ],
        ),
    ]
